package com.keda.minidao.entity;

// Generated 2018-6-7 15:13:48 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * WmsTrans generated by hbm2java
 */
public class WmsTrans implements java.io.Serializable {

	private Integer id;
	private String createName;
	private String createBy;
	private Date createDate;
	private String updateName;
	private String updateBy;
	private Date updateDate;
	private String sysOrgCode;
	private String sysCompanyCode;
	private String bpmStatus;
	private String transno;
	private Date transdate;
	private String transtype;
	private String goodsname;
	private Integer transqty;
	private String locno;
	private String zoneno;
	private String sourceid;
	private String sourcedtlid;
	private String trstatus;

	public WmsTrans() {
	}

	public WmsTrans(String createName, String createBy, Date createDate,
			String updateName, String updateBy, Date updateDate,
			String sysOrgCode, String sysCompanyCode, String bpmStatus,
			String transno, Date transdate, String transtype, String goodsname,
			Integer transqty, String locno, String zoneno, String sourceid,
			String sourcedtlid, String trstatus) {
		this.createName = createName;
		this.createBy = createBy;
		this.createDate = createDate;
		this.updateName = updateName;
		this.updateBy = updateBy;
		this.updateDate = updateDate;
		this.sysOrgCode = sysOrgCode;
		this.sysCompanyCode = sysCompanyCode;
		this.bpmStatus = bpmStatus;
		this.transno = transno;
		this.transdate = transdate;
		this.transtype = transtype;
		this.goodsname = goodsname;
		this.transqty = transqty;
		this.locno = locno;
		this.zoneno = zoneno;
		this.sourceid = sourceid;
		this.sourcedtlid = sourcedtlid;
		this.trstatus = trstatus;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getCreateName() {
		return this.createName;
	}

	public void setCreateName(String createName) {
		this.createName = createName;
	}

	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public String getUpdateName() {
		return this.updateName;
	}

	public void setUpdateName(String updateName) {
		this.updateName = updateName;
	}

	public String getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public String getSysOrgCode() {
		return this.sysOrgCode;
	}

	public void setSysOrgCode(String sysOrgCode) {
		this.sysOrgCode = sysOrgCode;
	}

	public String getSysCompanyCode() {
		return this.sysCompanyCode;
	}

	public void setSysCompanyCode(String sysCompanyCode) {
		this.sysCompanyCode = sysCompanyCode;
	}

	public String getBpmStatus() {
		return this.bpmStatus;
	}

	public void setBpmStatus(String bpmStatus) {
		this.bpmStatus = bpmStatus;
	}

	public String getTransno() {
		return this.transno;
	}

	public void setTransno(String transno) {
		this.transno = transno;
	}

	public Date getTransdate() {
		return this.transdate;
	}

	public void setTransdate(Date transdate) {
		this.transdate = transdate;
	}

	public String getTranstype() {
		return this.transtype;
	}

	public void setTranstype(String transtype) {
		this.transtype = transtype;
	}

	public String getGoodsname() {
		return this.goodsname;
	}

	public void setGoodsname(String goodsname) {
		this.goodsname = goodsname;
	}

	public Integer getTransqty() {
		return this.transqty;
	}

	public void setTransqty(Integer transqty) {
		this.transqty = transqty;
	}

	public String getLocno() {
		return this.locno;
	}

	public void setLocno(String locno) {
		this.locno = locno;
	}

	public String getZoneno() {
		return this.zoneno;
	}

	public void setZoneno(String zoneno) {
		this.zoneno = zoneno;
	}

	public String getSourceid() {
		return this.sourceid;
	}

	public void setSourceid(String sourceid) {
		this.sourceid = sourceid;
	}

	public String getSourcedtlid() {
		return this.sourcedtlid;
	}

	public void setSourcedtlid(String sourcedtlid) {
		this.sourcedtlid = sourcedtlid;
	}

	public String getTrstatus() {
		return this.trstatus;
	}

	public void setTrstatus(String trstatus) {
		this.trstatus = trstatus;
	}

}
